---
image: docker:stable-dind

services:
  - docker:dind

variables:
  PY_COLORS: 1
  TOXENF: py{38}-ansible-{previous,current}

before_script:
  - apk add --no-cache
    python3 python3-dev py3-pip gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh
  - python3 -m pip install tox --ignore-installed

molecule:
  script:
    - if [ -f tox.ini ] ; then image=${image} tag=${tag} tox ; else image=${image} tag=${tag} molecule test ; fi
  rules:
    - if: $CI_COMMIT_TAG == null
  retry: 2
  parallel:
    matrix:
      - image: "alpine"
        tag: "latest"
      - image: "amazonlinux"
        tag: "1"
      - image: "amazonlinux"
        tag: "latest"
      - image: "centos"
        tag: "7"
      - image: "centos"
        tag: "latest"
      - image: "debian"
        tag: "latest"
      - image: "debian"
        tag: "bullseye"
      - image: "fedora"
        tag: "32"
      - image: "fedora"
        tag: "latest"
      - image: "fedora"
        tag: "rawhide"
      - image: "ubuntu"
        tag: "latest"
      - image: "ubuntu"
        tag: "bionic"
      - image: "ubuntu"
        tag: "xenial"

galaxy:
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} ${CI_PROJECT_NAMESPACE} ${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_TAG != null
