- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"

- name: install software
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages }}"

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ services }}"

- name: create zone files
  template:
    src: templates/zone.j2
    dest: "{{ zonesdir }}/{{ zone }}.conf"
  with_items:
    - "{{ records }}"
  notify:
    reload zones
