---
# tasks file for dns
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ dns_packages }}"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dns_datadir }}"
    - "{{ dns_confdir }}"

- name: create group
  group:
    name: "{{ dns_group }}"
    state: present

- name: create user
  user:
    name: "{{ dns_owner }}"
    state: present
    system: yes

- name: generate rndc key
  command: rndc-confgen -a -c "{{ dns_confdir }}/rndc.key"
  args:
    creates: "{{ dns_confdir }}/rndc.key"

- name: set permissions on rndc key file
  file:
    path: "{{ dns_confdir }}/rndc.key"
    owner: "{{ dns_owner }}"
    group: "{{ dns_group }}"

- name: get most recent version of the hints/root file
  get_url:
    url: https://www.internic.net/domain/named.root
    dest: "{{ dns_datadir }}/named.root"
  when:
    - dns_caching_dns == true
  notify:
    reload zones

- name: create zone files
  template:
    src: zone.j2
    dest: "{{ dns_datadir }}/{{ item.name }}.conf"
  with_items:
    - "{{ dns_zones }}"
  notify:
    reload zones
  loop_control:
    label: "{{ item.name }}"

- name: add zones to configuration
  template:
    src: named.conf.j2
    dest: "{{ dns_confdir }}/named.conf"
    validate: named-checkconf -zj %s
  notify:
    reload configuration

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ dns_service }}"
  when:
    - ansible_virtualization_type != "docker"
