---
# tasks file for ansible-role-dns
- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"

- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ zonesdir }}"
    - "{{ confdir }}"

- name: get most recent version of the hints/root file
  get_url:
    url: ftp://ftp.internic.net/domain/named.root
    dest: "{{ zonesdir }}/named.root"
  when:
    - caching_dns == true
  notify:
    reload zones

- name: create zone files
  template:
    src: templates/zone.j2
    dest: "{{ zonesdir }}/{{ item.name }}.conf"
  with_items:
    - "{{ zones }}"
  notify:
    reload zones

- name: add zones to configuration
  template:
    src: templates/named.conf.j2
    dest: "{{ confdir }}/named.conf"
  notify:
    reload configuration

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ services }}"
  when:
    - ansible_virtualization_type != "docker"
