- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"

- name: install software
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages }}"

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ services }}"

- name: get most recent version of the hints/root file
  get_url:
    url: ftp://ftp.internic.net/domain/named.root
    path: "{{ zonesdir }}/named.root"

- name: create zone files
  template:
    src: templates/zone.j2
    dest: "{{ zonesdir }}/{{ item.name }}.conf"
  with_items:
    - "{{ zones }}"
  notify:
    reload zones

- name: add zones to configuration
  template:
    src: templates/named.conf.j2
    dest: "{{ confdir }}/named.conf"
  notify:
    reload configuration
