---
# tasks file for dns
- name: install dns
  package:
    name: "{{ dns_packages[ansible_distribution]
          | default(dns_packages['default']) }}"
    state: "{{ dns_package_state }}"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dns_datadir[ansible_distribution]
      | default(dns_datadir['default']) }}"
    - "{{ dns_confdir[ansible_distribution]
      | default(dns_confdir['default']) }}"

- name: create group
  group:
    name: "{{ dns_group[ansible_distribution]
          | default(dns_group['default']) }}"
    state: present

- name: create user
  user:
    name: "{{ dns_owner[ansible_distribution]
          | default(dns_owner['default']) }}"
    state: present
    system: yes

- name: generate rndc key
  command: rndc-confgen -a -c "{{ dns_confdir[ansible_distribution]
           | default(dns_confdir['default']) }}/rndc.key"
  args:
    creates: "{{ dns_confdir[ansible_distribution]
             | default(dns_confdir['default']) }}/rndc.key"

- name: set permissions on rndc key file
  file:
    path: "{{ dns_confdir[ansible_distribution]
          | default(dns_confdir['default']) }}/rndc.key"
    owner: "{{ dns_owner[ansible_distribution]
           | default(dns_owner['default']) }}"
    group: "{{ dns_group[ansible_distribution]
           | default(dns_group['default']) }}"

- name: get most recent version of the hints/root file
  get_url:
    url: https://www.internic.net/domain/named.root
    dest: "{{ dns_datadir[ansible_distribution]
          | default(dns_datadir['default']) }}/named.root"
  when:
    - dns_caching_dns
  notify:
    reload zones

- name: create zone files
  template:
    src: zone.j2
    dest: "{{ dns_datadir[ansible_distribution]
          | default(dns_datadir['default']) }}/{{ item.name }}.conf"
  with_items:
    - "{{ dns_zones }}"
  notify:
    reload zones
  loop_control:
    label: "{{ item.name }}"

- name: add zones to configuration
  template:
    src: named.conf.j2
    dest: "{{ dns_confdir[ansible_distribution]
          | default(dns_confdir['default']) }}/named.conf"
    validate: named-checkconf -zj %s
  notify:
    reload configuration

- name: start and enable dns
  service:
    name: "{{ dns_service[ansible_distribution]
          | default(ansible_distribution['default']) }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
