---
# tasks file for dns
- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"

- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ dns_packages }}"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dns_zonesdir }}"
    - "{{ dns_confdir }}"

- name: generate rndc key
  command: rndc-confgen -a
  args:
    creates: "{{ dns_confdir }}/rndc.key"

- name: get most recent version of the hints/root file
  get_url:
    url: ftp://ftp.internic.net/domain/named.root
    dest: "{{ dns_zonesdir }}/named.root"
  when:
    - dns_caching_dns == true
  notify:
    reload zones

- name: create zone files
  template:
    src: templates/zone.j2
    dest: "{{ dns_zonesdir }}/{{ item.name }}.conf"
  with_items:
    - "{{ dns_zones }}"
  notify:
    reload zones

- name: add zones to configuration
  template:
    src: templates/named.conf.j2
    dest: "{{ dns_confdir }}/named.conf"
  notify:
    reload configuration

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ dns_services }}"
  when:
    - ansible_virtualization_type != "docker"
