---
# handlers file for ansible-role-dns
- name: reload zones
  command: rndc reload

- name: reload configuration
  command: named-checkconf -zj
  notify:
    really reload configuration

- name: really reload configuration
  command: rndc reload
